------- Generated by SYS.DBMS_METADATA on 01/12/2017 at 08:25:50 -------

  CREATE OR REPLACE FUNCTION F_DESVIO_PADRAO (pconjunto_valores varchar2) RETURN NUMBER
AS
vsconjunto varchar2(1000);
vssignificar number(18,2);
vsN number(18);
vsVariancia varchar(1000);
vsTempVariancia number(18,2);
vsSquared number(18,2);
vsVariacao number(18,2);
vsDesvioPadrao number(18,4);
BEGIN 
vsconjunto := pconjunto_valores;
SELECT count(*) INTO vsN FROM table(split(',', vsconjunto));
SELECT
    (SELECT sum(column_value) FROM table(SPLIT(',',vsconjunto))) / vsN INTO vssignificar
FROM dual;

--encontrar a variancia
FOR data IN (SELECT column_value valor FROM table(SPLIT(',',vsconjunto)))
LOOP
vsTempVariancia := data.valor - vssignificar;

vsTempVariancia := (vsTempVariancia * vsTempVariancia);
vsVariancia := vsVariancia||vsTempVariancia ||',';

END LOOP;


vsVariancia := SUBSTR(vsVariancia, 1, length(vsVariancia) - 1);
SELECT sum(column_value) INTO vsSquared FROM table(SPLIT(',',vsVariancia));
vsVariacao := vsSquared / (vsN-1);
vsDesvioPadrao := SQRT(vsVariacao);
dbms_output.put_line(vsDesvioPadrao);
RETURN vsDesvioPadrao;
END;
/
