------- Generated by SYS.DBMS_METADATA on 01/12/2017 at 08:25:05 -------

  CREATE OR REPLACE FUNCTION SPLIT (delimitador IN VARCHAR2, exp_string IN VARCHAR2)
RETURN lista AS
   l_string LONG DEFAULT exp_string || delimitador;
   l_data lista:= lista ();
   cont NUMBER;
BEGIN
   LOOP
   EXIT WHEN l_string IS NULL;
      cont := INSTR (l_string, delimitador);
      l_data.EXTEND;
      l_data (l_data.COUNT) := LTRIM (RTRIM (SUBSTR (l_string, 1, cont - 1)));
      l_string := SUBSTR (l_string, cont + 1);
   END LOOP;
   RETURN l_data;
END;
/
